#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8
sudo cp /etc/hosts /etc/hosts.bak
sudo sed -i 's/127.0.0.1\slocalhost/127.0.0.2 localhost/' /etc/hosts
echo "8.8.8.8           facebook.com" | sudo tee -a /etc/hosts
cat /etc/hosts
