#!/usr/bin/env bash

# Set the hostname
sudo hostnamectl set-hostname your_hostname

# Get the current IP address
current_ip=$(grep -oP '(?<=\s)localhost' /etc/hosts | awk '{print $1}')

# Backup the hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Modify hosts file
sudo sed -i 's/127.0.0.1\slocalhost/127.0.0.2 localhost/' /etc/hosts
echo "8.8.8.8           facebook.com" | sudo tee -a /etc/hosts

# Set the hostname in the hosts file
sudo sed -i "s/$current_ip\s$(hostname)/127.0.0.2 $(hostname)/" /etc/hosts

# Display the new hosts file
cat /etc/hosts

# Restart networking to apply changes
sudo service networking restart

